###
GET http://localhost:3000/

###
GET http://localhost:3000/pets

###
GET http://localhost:3000/pets/0

###
GET http://localhost:3000/pets/1

###
GET http://localhost:3000/pets/2

###
GET http://localhost:3000/pets/-1

###
POST http://localhost:3000/pets

{
    "age": 3,
    "kind": "parakeet",
    "name": "Cornflake"
}